name: Deploy

on:
  push:
    branches: [ main ]

env:
  REPO_NAME: myrepo
  IMAGE_VERSION: 1.1
  IMAGE_NAME: webapp

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build Docker images
      run: docker build -t $IMAGE_NAME:$IMAGE_VERSION -f Dockerfile .

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # - name: Push images to Docker hub
    #   run: |
    #     docker tag $IMAGE_NAME:$IMAGE_VERSION ${{ secrets.DOCKER_USERNAME }}/$REPO_NAME
    #     docker push ${{ secrets.DOCKER_USERNAME }}/$REPO_NAME

  deploy:
    runs-on: self-hosted
    steps:       
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          touch test1.txt
